---
abstract: 'A wrapper for installing the Judy library'
author: []
build_requires:
  Cwd: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Liblist: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  Module::Build: 0
  Sub::Exporter: 0
  Test::More: 0
  lib: 0
  perl: 5.005
  vars: 0
  warnings: 0
configure_requires:
  Cwd: 0
  ExtUtils::Liblist: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  Module::Build: 0
  Sub::Exporter: 0
  lib: 0
  perl: 5.005
  vars: 0
  warnings: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-Judy
provides:
  Alien::Judy:
    file: lib/Alien/Judy.pm
    version: 0.20
requires:
  Cwd: 0
  ExtUtils::CBuilder: 0
  ExtUtils::Liblist: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  Module::Build: 0
  Sub::Exporter: 0
  Test::More: 0
  lib: 0
  perl: 5.005
  vars: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
