---
name: Alien-Judy
version: 0.05
author:
  - 'Joshua ben Jore <jjore@cpan.org>'
abstract: A wrapper for installing the Judy library
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Alien::Judy:
    file: lib/Alien/Judy.pm
    version: 0.05
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
